# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3

# Mod Properties
mod_version=1.2.5
maven_group=nl.theepicblock
archives_base_name=proper-pet-tp

# Dependencies
fabric_version=0.153.0+26.2

modrinth_project=ppetp
